// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBogCkLlistLv348VvL0pWyj7zWlkhURGA',
    appId: '1:209392306167:web:d578d636a2dad2b27550f2',
    messagingSenderId: '209392306167',
    projectId: 'legitcards-3029d',
    authDomain: 'legitcards-3029d.firebaseapp.com',
    storageBucket: 'legitcards-3029d.firebasestorage.app',
    measurementId: 'G-P6RLL7HGNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCOcPumIVc02xUYmQfkCd1IpOsyVZBLho',
    appId: '1:209392306167:android:af45ef204c808df77550f2',
    messagingSenderId: '209392306167',
    projectId: 'legitcards-3029d',
    storageBucket: 'legitcards-3029d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6uYzf00nOxHWGwwUmNfwt2_iuBeeJX8U',
    appId: '1:209392306167:ios:235e58b1527bce087550f2',
    messagingSenderId: '209392306167',
    projectId: 'legitcards-3029d',
    storageBucket: 'legitcards-3029d.firebasestorage.app',
    iosBundleId: 'com.legitcardsusers.legitCards',
  );
}
